# Generated by Django 4.0.5 on 2022-07-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_rename_file_workview_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='MostPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='OurFavourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
    ]
