# Generated by Django 4.0.5 on 2022-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_latestwork_mostpopular_ourfavourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehindTheScenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
    ]
