# Generated by Django 4.0.5 on 2022-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_behindthescenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behindthescenes',
            old_name='name',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='latestwork',
            old_name='name',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='mostpopular',
            old_name='name',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='ourfavourites',
            old_name='name',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='workview',
            old_name='name',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='behindthescenes',
            name='Desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500),
        ),
        migrations.AddField(
            model_name='behindthescenes',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='latestwork',
            name='Desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500),
        ),
        migrations.AddField(
            model_name='latestwork',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='mostpopular',
            name='Desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500),
        ),
        migrations.AddField(
            model_name='mostpopular',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='ourfavourites',
            name='Desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500),
        ),
        migrations.AddField(
            model_name='ourfavourites',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='workview',
            name='Desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500),
        ),
        migrations.AddField(
            model_name='workview',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
