# Generated by Django 4.0.5 on 2022-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehindTheScenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Desc', models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500)),
                ('link', models.URLField(default='#')),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='LatestWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Desc', models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500)),
                ('link', models.URLField(default='#')),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='MostPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Desc', models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500)),
                ('link', models.URLField(default='#')),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='OurFavourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Desc', models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500)),
                ('link', models.URLField(default='#')),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
        migrations.RenameField(
            model_name='workview',
            old_name='name',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='workview',
            old_name='file',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='workview',
            name='Desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500),
        ),
        migrations.AddField(
            model_name='workview',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
