# Generated by Django 4.0.5 on 2022-07-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_behindthescenes_latestwork_mostpopular_ourfavourites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behindthescenes',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='latestwork',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='mostpopular',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='ourfavourites',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='workview',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
