# Generated by Django 4.0.5 on 2022-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_alter_behindthescenes_link_alter_latestwork_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stories_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Desc', models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia', max_length=500)),
                ('link', models.URLField(default='http://127.0.0.1:8000/')),
                ('image_file', models.FileField(default='', upload_to='images')),
            ],
        ),
    ]
